config/routes.rb
Rails.application.routes.draw do
  get 'items/items_sold' => 'items#items_sold'

  get 'items/items_for_sale' => 'items#items_for_sale'

  root 'welcome#index'

  resources :items do
    member do
      patch :mark_as_sold
      get :download_item_image
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base

  mount_uploader :item_image, ItemUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @new_item = Item.new
  end

  def create
    @new_item = Item.new(item_params)

    if @new_item.save
      redirect_to items_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    end
  end

  def destroy
    @item = Item.find(params[:id])

    if @item.delete
      redirect_to items_path
    end
  end

  def items_sold
    @items = Item.where(:sold => true)
  end

  def items_for_sale
    @items = Item.where(:sold => false)
  end

  def mark_as_sold
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to items_path
    end
  end

  def download_item_image
    @item = Item.find(params[:id])
    file = @item.item_image
    send_file file.path
  end

  private

  def item_params
    params.require(:item).permit!
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.haml
%form

  .form-group
    .col-sm-12
      = f.label  :name
      = f.text_field :name, class: "form-control"

      = f.label :description
      = f.text_area :description, class: "form-control"

      = f.label "Price, in cents"
      = f.text_field :price, class: "form-control"
     
      = f.label "How old is this item in years?"
      = f.text_field :age, class: "form-control"

      = f.label :awesome_rating
      = f.select :awesome_rating, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], {}, {class: "form-control" } 

      = f.label :item_image
      = f.file_field :item_image

      %button.btn.btn-primary.form-control.my_edit_button{type: "submit"} Submit

      %p

-if @item
  .col-sm-12
    = button_to 'Delete this Item', "/items/#{@item.id}", method: "delete", data: { confirm: "Are you sure?" }, class: "btn btn-primary form-control"

app/views/items/edit.html.haml
%h3 Edit this item
= form_for @item, url: "/items/#{@item.id}", action: "PUT" do |f|
  =render "form", f: f

app/views/items/index.html.haml
%h1.title2 All of the items for sale (and sold ):

.row
  -@items.each do |item|
    .col-lg-4.col-md-4.col-sm-4
      .panel.panel-default
        
  
        .row
          .col-lg-6.col-md-6.col-sm-6
            = image_tag item.item_image.url, :class => "item_image .navbar-left"
          .col-lg-6.col-md-6.col-sm-6
            %h5.title= link_to item.name, "items/#{item.id}", class: "title_link"
        .text
          %p= "#{item.description}"
          %p= "Price: #{item.price}"
          %p= "Age: #{item.age}"
          %p= "Level de awesome: #{item.awesome_rating}"
          -unless item.sold
            = form_for item, url: "/items/#{item.id}/mark_as_sold", action: "PATCH" do |f|
              =f.hidden_field :sold, :value => "true"
              =f.submit "Mark as Sold"
          -else
            %p.sold= "Sold"

app/views/items/items_for_sale.html.haml
%h1.title2 All the items still for sale at my garage sale:

.row
  -@items.each do |item|
    .col-lg-4.col-md-4.col-sm-4
      .panel.panel-default
        
  
        .row
          .col-lg-5.col-md-5.col-sm-5
            = image_tag item.item_image.url, :class => "item_image .navbar-left"
          .col-lg-6.col-md-6.col-sm-6
            %h5.title= link_to item.name, "/items/#{item.id}", class: "title_link"
        .text
          %p= "#{item.description}"
          %p= "Price: #{item.price}"
          %p= "Age: #{item.age}"
          %p= "Level de awesome: #{item.awesome_rating}"
          -unless item.sold
            = form_for item, url: "/items/#{item.id}/mark_as_sold", action: "PATCH" do |f|
              =f.hidden_field :sold, :value => "true"
              =f.submit "Mark as Sold"
          -else
            %p.sold= "Sold"

app/views/items/items_sold.html.haml
%h1.title2 These are the all of the items sold at my garage sale:

.row
  -@items.each do |item|
    .col-lg-4.col-md-4.col-sm-4
      .panel.panel-default
        
  
        .row
          .col-lg-5.col-md-5.col-sm-5
            = image_tag item.item_image.url, :class => "item_image .navbar-left"
          .col-lg-6.col-md-6.col-sm-6
            %h5.title= link_to item.name, "/items/#{item.id}", class: "title_link"
        .text
          %p= "#{item.description}"
          %p= "Price: #{item.price}"
          %p= "Age: #{item.age}"
          %p= "Level de awesome: #{item.awesome_rating}"
          -unless item.sold
            = form_for item, url: "/items/#{item.id}/mark_as_sold", action: "PATCH" do |f|
              =f.hidden_field :sold, :value => "true"
              =f.submit "Mark as Sold"
          -else
            %p.sold= "Sold"

app/views/items/new.html.haml
%h3 Add your item
= form_for @new_item, url: "/items" do |f|
  =render "form", f: f

app/views/items/show.html.haml
.col-lg8.col-md-8.col-sm-8.col-sm-offset-2.col-md-offset-2.col-lg-offset-2
  .panel.panel-default.centered
    .panel-body
      = image_tag @item.item_image.url, :class => "item_image .navbar-left padded_right"
      .show_page_top_text
        %h1= @item.name
        %h4= "Description: #{@item.description}"
      %p= "Price: #{@item.price}"
      %p= "Age: #{@item.age}"
      %p= "Age: #{@item.awesome_rating}" 
      %br
  %p= link_to "Download Image", download_item_image_item_path, class: "btn btn-primary form-control"
  %p= link_to "Edit", "/items/#{@item.id}/edit", class: "btn btn-primary form-control"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GarageSale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="/">Garage Sale</a>
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>



    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="/items">All Items</a>
        </li>
        <li class="">
          <a href="/items/items_for_sale">Items for Sale</a>
        </li>
        <li>
          <a href="/items/items_sold">Items already Sold</a>
        </li>
        <li>
          <a href="/items/new">Add a New Item</a>
        </li>
      </ul>
    </nav>
  </div>
</div>


<div class="add_top_margin container">
  <div class="row">
    <%= yield %>
  </div>
</div>


<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/welcome/index.html.erb
</div>
  <h1>Welcome to the make-believe old school video game garage sale</h1>
  <p>Feel free to take a look around. Click away!</p>